# Generated by Django 5.2.15 on 2026-07-04 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.TextField(blank=True, null=True)),
                ('platform', models.CharField(default='Simulator', max_length=50)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('query', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(default=5)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.TextField()),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('sentiment_label', models.CharField(max_length=20)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='analyzer.product')),
            ],
        ),
    ]
